In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("train.csv")
df2 = pd.read_csv("toxicity_800k.csv")

In [3]:
print(df1.columns)
print(df2.columns)

Index(['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate'],
      dtype='str')
Index(['Unnamed: 0', 'text', 'toxicity', 'severe_toxicity', 'obscene',
       'threat', 'insult', 'identity_attack', 'sexual_explicit'],
      dtype='str')

In [4]:
df2 = df2.rename(columns={
    'text':'comment_text',
    'toxicity':'toxic',
    'severe_toxicity':'severe_toxic',
    'identity_attack':'identity_hate'
})

df2 = df2.drop(columns=['Unnamed: 0','sexual_explicit'])


print(df1.columns)
print(df2.columns)

Index(['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate'],
      dtype='str')
Index(['comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat', 'insult',
       'identity_hate'],
      dtype='str')

In [5]:
df = pd.concat([df1,df2],ignore_index=True)

In [6]:
df.head(10)

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0.0,0.0,0.0,0.0,0.0,0.0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0.0,0.0,0.0,0.0,0.0,0.0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0.0,0.0,0.0,0.0,0.0,0.0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0.0,0.0,0.0,0.0,0.0,0.0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0.0,0.0,0.0,0.0,0.0,0.0
5,00025465d4725e87,"""\n\nCongratulations from me as well, use the ...",0.0,0.0,0.0,0.0,0.0,0.0
6,0002bcb3da6cb337,COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK,1.0,1.0,1.0,0.0,1.0,0.0
7,00031b1e95af7921,Your vandalism to the Matt Shirvington article...,0.0,0.0,0.0,0.0,0.0,0.0
8,00037261f536c51d,Sorry if the word 'nonsense' was offensive to ...,0.0,0.0,0.0,0.0,0.0,0.0
9,00040093b2687caa,alignment on this subject and which are contra...,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
df.shape

(259571, 8)

In [8]:
df.columns

Index(['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate'],
      dtype='str')

In [9]:
df.drop(columns=["id"],inplace=True)

In [10]:
df.columns

Index(['comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat', 'insult',
       'identity_hate'],
      dtype='str')

In [11]:
df.describe

<bound method NDFrame.describe of                                              comment_text  toxic  \
0       Explanation\nWhy the edits made under my usern...    0.0
1       D'aww! He matches this background colour I'm s...    0.0
2       Hey man, I'm really not trying to edit war. It...    0.0
3       "\nMore\nI can't make any real suggestions on ...    0.0
4       You, sir, are my hero. Any chance you remember...    0.0
...                                                   ...    ...
259566  EdmondL,\n"He excites a lot of morons by abusi...    0.6
259567  Russia is  a terrorist state, the fascist regi...    0.9
259568  Jim O'Neil. Thank you for your example of "mor...    0.2
259569  You know who would do well on this show? Kevin...    0.0
259570  The incompetent government should get out of t...    0.5

        severe_toxic  obscene  threat  insult  identity_hate
0                0.0      0.0     0.0     0.0            0.0
1                0.0      0.0     0.0     0.0            0.0
2                0.0      0.0     0.0     0.0            0.0
3                0.0      0.0     0.0     0.0            0.0
4                0.0      0.0     0.0     0.0            0.0
...              ...      ...     ...     ...            ...
259566           0.1      0.1     0.0     0.5            0.2
259567           0.2      0.2     0.0     0.8            0.6
259568           0.0      0.0     0.2     0.0            0.0
259569           0.0      0.0     0.0     0.0            0.0
259570           0.0      0.0     0.0     0.6            0.1

[259571 rows x 7 columns]>

In [12]:
df.info

<bound method DataFrame.info of                                              comment_text  toxic  \
0       Explanation\nWhy the edits made under my usern...    0.0
1       D'aww! He matches this background colour I'm s...    0.0
2       Hey man, I'm really not trying to edit war. It...    0.0
3       "\nMore\nI can't make any real suggestions on ...    0.0
4       You, sir, are my hero. Any chance you remember...    0.0
...                                                   ...    ...
259566  EdmondL,\n"He excites a lot of morons by abusi...    0.6
259567  Russia is  a terrorist state, the fascist regi...    0.9
259568  Jim O'Neil. Thank you for your example of "mor...    0.2
259569  You know who would do well on this show? Kevin...    0.0
259570  The incompetent government should get out of t...    0.5

        severe_toxic  obscene  threat  insult  identity_hate
0                0.0      0.0     0.0     0.0            0.0
1                0.0      0.0     0.0     0.0            0.0
2                0.0      0.0     0.0     0.0            0.0
3                0.0      0.0     0.0     0.0            0.0
4                0.0      0.0     0.0     0.0            0.0
...              ...      ...     ...     ...            ...
259566           0.1      0.1     0.0     0.5            0.2
259567           0.2      0.2     0.0     0.8            0.6
259568           0.0      0.0     0.2     0.0            0.0
259569           0.0      0.0     0.0     0.0            0.0
259570           0.0      0.0     0.0     0.6            0.1

[259571 rows x 7 columns]>

In [13]:
df.dtypes

comment_text         str
toxic            float64
severe_toxic     float64
obscene          float64
threat           float64
insult           float64
identity_hate    float64
dtype: object

In [14]:
non_str= df.drop(columns=['comment_text'])

In [15]:
non_str.isnull().sum()

toxic            1
severe_toxic     1
obscene          1
threat           1
insult           1
identity_hate    1
dtype: int64

In [16]:
non_str.head()

   toxic  severe_toxic  obscene  threat  insult  identity_hate
0    0.0           0.0      0.0     0.0     0.0            0.0
1    0.0           0.0      0.0     0.0     0.0            0.0
2    0.0           0.0      0.0     0.0     0.0            0.0
3    0.0           0.0      0.0     0.0     0.0            0.0
4    0.0           0.0      0.0     0.0     0.0            0.0

In [17]:
df.drop_duplicates

<bound method DataFrame.drop_duplicates of                                              comment_text  toxic  \
0       Explanation\nWhy the edits made under my usern...    0.0
1       D'aww! He matches this background colour I'm s...    0.0
2       Hey man, I'm really not trying to edit war. It...    0.0
3       "\nMore\nI can't make any real suggestions on ...    0.0
4       You, sir, are my hero. Any chance you remember...    0.0
...                                                   ...    ...
259566  EdmondL,\n"He excites a lot of morons by abusi...    0.6
259567  Russia is  a terrorist state, the fascist regi...    0.9
259568  Jim O'Neil. Thank you for your example of "mor...    0.2
259569  You know who would do well on this show? Kevin...    0.0
259570  The incompetent government should get out of t...    0.5

        severe_toxic  obscene  threat  insult  identity_hate
0                0.0      0.0     0.0     0.0            0.0
1                0.0      0.0     0.0     0.0            0.0
2                0.0      0.0     0.0     0.0            0.0
3                0.0      0.0     0.0     0.0            0.0
4                0.0      0.0     0.0     0.0            0.0
...              ...      ...     ...     ...            ...
259566           0.1      0.1     0.0     0.5            0.2
259567           0.2      0.2     0.0     0.8            0.6
259568           0.0      0.0     0.2     0.0            0.0
259569           0.0      0.0     0.0     0.0            0.0
259570           0.0      0.0     0.0     0.6            0.1

[259571 rows x 7 columns]>

In [18]:
df['comment_text'].isnull().sum()

np.int64(0)

In [19]:
import re
import html

def clean_comment(text):
    text = html.unescape(text)


    text = text.lower()

    text = re.sub(r"https?://\S+|www\.\S+", " ", text)

    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"\b(?:\d{1,3}\.){3}\d{1,3}\b", " ", text)

    text = re.sub(r"=+\s*.*?\s*=+", " ", text)

    text = re.sub(r"[\r\n\t]+", " ", text)

    text = re.sub(r"\s+", " ", text).strip()

    return text

df['cleaned_text'] = df['comment_text'].apply(clean_comment)

In [20]:
df.head()

,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate,cleaned_text
0,Explanation\nWhy the edits made under my usern...,0.0,0.0,0.0,0.0,0.0,0.0,explanation why the edits made under my userna...
1,D'aww! He matches this background colour I'm s...,0.0,0.0,0.0,0.0,0.0,0.0,d'aww! he matches this background colour i'm s...
2,"Hey man, I'm really not trying to edit war. It...",0.0,0.0,0.0,0.0,0.0,0.0,"hey man, i'm really not trying to edit war. it..."
3,"""\nMore\nI can't make any real suggestions on ...",0.0,0.0,0.0,0.0,0.0,0.0,""" more i can't make any real suggestions on im..."
4,"You, sir, are my hero. Any chance you remember...",0.0,0.0,0.0,0.0,0.0,0.0,"you, sir, are my hero. any chance you remember..."

In [21]:
df.drop(columns=['comment_text'], inplace=True)

In [22]:
df.head()

,toxic,severe_toxic,obscene,threat,insult,identity_hate,cleaned_text
0,0.0,0.0,0.0,0.0,0.0,0.0,explanation why the edits made under my userna...
1,0.0,0.0,0.0,0.0,0.0,0.0,d'aww! he matches this background colour i'm s...
2,0.0,0.0,0.0,0.0,0.0,0.0,"hey man, i'm really not trying to edit war. it..."
3,0.0,0.0,0.0,0.0,0.0,0.0,""" more i can't make any real suggestions on im..."
4,0.0,0.0,0.0,0.0,0.0,0.0,"you, sir, are my hero. any chance you remember..."

In [23]:
original_cols = [
    "toxic",
    "severe_toxic",
    "obscene",
    "threat",
    "insult",
    "identity_hate"
]

for col in original_cols:
    df[col + "_label"] = (df[col] > 0.5).astype(int)

In [24]:
target_cols = [col + "_label" for col in original_cols]

X = df["cleaned_text"]
y = df[target_cols]

from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.15,
    random_state=42
)

In [25]:
# Columns containing the original continuous toxicity scores
score_cols = [
    "toxic",
    "severe_toxic",
    "obscene",
    "threat",
    "insult",
    "identity_hate"
]

# Create new binary training columns
for col in score_cols:
    # Preserve original continuous values
    df[f"{col}_score"] = df[col]

    # Create binary classification target
    df[f"{col}_label"] = (df[f"{col}_score"] >= 0.5).astype(int)

In [26]:
y_train = y_train.fillna(0)
y_val = y_val.fillna(0)

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import FeatureUnion

vectorizer = FeatureUnion([
    ("word_tfidf", TfidfVectorizer(
        ngram_range=(1, 2),
        max_features=30000,
        sublinear_tf=True
    )),
    ("char_tfidf", TfidfVectorizer(
        ngram_range=(2, 6),
        analyzer="char",
        max_features=40000,
        sublinear_tf=True
    ))
])

X_train_vec = vectorizer.fit_transform(X_train)
X_val_vec = vectorizer.transform(X_val)

print(f"Total features created: {X_train_vec.shape[1]:,}")

Total features created: 70,000

In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

models = {}
val_probs = {}

print("Training 6 multi-label classifiers...")
for col in target_cols:
    print(f"--> Training classifier for: {col}")
    clf = LogisticRegression(
        C=2.5,
        max_iter=200,
        class_weight="balanced",
        solver="saga",
        n_jobs=-1
    )
    clf.fit(X_train_vec, y_train[col])
    models[col] = clf
    val_probs[col] = clf.predict_proba(X_val_vec)[:, 1]

print("\nAll models trained successfully!")

Training 6 multi-label classifiers...
--> Training classifier for: toxic_label

c:\Users\Anmol\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1435: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)
c:\Users\Anmol\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Anmol\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1435: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

--> Training classifier for: severe_toxic_label

c:\Users\Anmol\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Anmol\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1435: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

--> Training classifier for: obscene_label

c:\Users\Anmol\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Anmol\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1435: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

--> Training classifier for: threat_label

c:\Users\Anmol\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Anmol\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1435: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

--> Training classifier for: insult_label

c:\Users\Anmol\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Anmol\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1435: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

--> Training classifier for: identity_hate_label

All models trained successfully!

c:\Users\Anmol\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

In [29]:
import numpy as np

print("=== Validation ROC-AUC Scores ===")
auc_scores = []
for col in target_cols:
    auc = roc_auc_score(y_val[col], val_probs[col])
    auc_scores.append(auc)
    print(f"{col:15} | ROC-AUC: {auc:.4f}")

print(f"\nAverage ROC-AUC: {np.mean(auc_scores):.4f}")

=== Validation ROC-AUC Scores ===
toxic_label     | ROC-AUC: 0.9592
severe_toxic_label | ROC-AUC: 0.9815
obscene_label   | ROC-AUC: 0.9788
threat_label    | ROC-AUC: 0.9592
insult_label    | ROC-AUC: 0.9604
identity_hate_label | ROC-AUC: 0.9646

Average ROC-AUC: 0.9673

In [30]:
import joblib

import os

os.makedirs("model2", exist_ok=True)

joblib.dump(clf,"model2.pkl")
for col in target_cols:
    joblib.dump(models[col], f"model2/{col}.pkl")

In [32]:
import os
import joblib

os.makedirs("model1", exist_ok=True)

# 1. TF-IDF vectorizer
joblib.dump(
    vectorizer,
    "model1/tfidf_vectorizer.joblib"
)

# 2. Six trained classifiers
joblib.dump(
    models,
    "model1/toxicity_models.joblib"
)

# 3. Label names
joblib.dump(
    target_cols,
    "model1/target_columns.joblib"
)

print("All model artifacts saved successfully!")

All model artifacts saved successfully!

In [34]:
import joblib

complete_model = {
    "vectorizer": vectorizer,
    "models": models,
    "target_cols": list(target_cols),
    "threshold": 0.5
}

joblib.dump(
    complete_model,
    "model1/scrollshield_toxicity_model.joblib"
)

print("Saved complete model setup!")

Saved complete model setup!